CengZai.Web/Controllers/OAuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CengZai.Model;
using CengZai.Helper;
using CengZai.Web.Common;
using System.Text.RegularExpressions;
using System.Web.Security;
using System.Text;
using CengZai.OAuthSDK.QQ;
using CengZai.OAuthSDK.Sina;

namespace CengZai.Web.Controllers
{
    public class OAuthController : BaseController
    {
        // QQ登录页面 
        [HttpGet]
        public ActionResult QQLogin()
        {
            Model.User loginUser = GetLoginUser();
            if (loginUser == null)
            {
                var qqApi = new QQApi();
                string state = Guid.NewGuid().ToString().Replace("-", "");
                Session["requeststate"] = state;
                string scope = "get_user_info,add_share,list_album,upload_pic,check_page_fans,add_t,add_pic_t,del_t,get_repost_list,get_info,get_other_info,get_fanslist,get_idolist,add_idol,del_idol,add_one_blog,add_topic,get_tenpay_addr";
                var authenticationUrl = qqApi.GetAuthorizationUrl(state, scope);
                return new RedirectResult(authenticationUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }


        // 回调页面 
        public ActionResult QQCallback()
        {
            if (Request.Params["code"] != null)
            {
                var qqApi = new QQApi();
                var code = Request.Params["code"];
                var state = Request.Params["state"];
                string requestState = Session["requeststate"].ToString();
                if (state == requestState)
                {
                    qqApi.GetAccessToken(code);
                    var currentUser = qqApi.GetUserInfo();
                    string openId = qqApi.Token.Uid;
                    if (currentUser == null || string.IsNullOrEmpty(openId))
                    {
                        return JumpToTips("登录失败！", "授权错误！请稍后重试！");
                    }
                    BLL.User bllUser = new BLL.User();
                    Model.User mUser = bllUser.GetModelByOpenId(openId, Model.LoginType.QQ);
                    if (mUser == null)
                    {
                        mUser = new Model.User();
                        mUser.AreaID = 0;
                        mUser.Avatar = currentUser.figureurl_2;
                        mUser.Birth = null;
                        mUser.Email = "";
                        mUser.Intro = "";
                        mUser.LoginCount = 0;
                        mUser.LoginIp = "";
                        mUser.LoginTime = null;
                        mUser.Mobile = "";
                        mUser.Username = "";
                        mUser.Nickname = currentUser.nickname;
                        mUser.Password = "";
                        mUser.Privacy = 0;
                        mUser.RegIp = Helper.Util.GetIP();
                        mUser.RegTime = DateTime.Now;
                        mUser.Sex = (currentUser.gender == "男" ? 1 : 2);
                        mUser.Sign = "此家伙不懒，就是什么也没留下";
                        mUser.State = 0;
                        mUser.Vip = 0;
                        mUser.Credit = 5;   //初次登录赠送5个积分
                        mUser.Money = 0;
                        mUser.Config = new UserConfig();
                        //用户尚未注册
                        mUser.LoginType = Model.LoginType.QQ;
                        mUser.AccessToken = qqApi.Token.AccessToken;
                        mUser.OpenId = openId;
                        mUser.AuthTime = DateTime.Now;
                        mUser.UserID = bllUser.Add(mUser);
                    }
                    else
                    {
                        switch (Config.LoginLimit)
                        {
                            //禁止所有用户登录
                            case 2:
                                return JumpToTips("Error", "系统正在维护，暂停登录，请稍后再试！");
                            //break;

                            //只有激活用户可以登录
                            case 1:
                                if (mUser.State == 0)
                                {
                                    return JumpToTips("Error", "您的帐号尚未激活，请先登录邮箱激活帐号！");
                                }
                                else if (mUser.State == -1)
                                {
                                    return JumpToTips("Error", "您的帐号被冻结，暂时无法登录！");
                                }
                                break;

                            //全部用户可以登录，包括锁定用户
                            case -1:
                                //全部用户可以登录
                                break;

                            //非锁定用户可以登录
                            case 0:
                            default:
                                if (mUser.State == -1)
                                {
                                    return JumpToTips("Error", "您的帐号被冻结，暂时无法登录！");
                                }
                                break;
                        }
                        
                    }
                    //更新登录用户信息，写入Cookies和Session登录
                    UpdateLoginUserInfo(mUser);
                    UpdateLoginUserCookie(mUser, false);
                    UpdateLoginUserSession(mUser);

                    if (string.IsNullOrEmpty(mUser.Email) || string.IsNullOrEmpty(mUser.Username))
                    {
                        return RedirectToAction("Register");
                    }
                    else
                    {
                        return JumpToHome("登录成功！", "正在为您跳转到首页...");
                    }
                }
            }
            return JumpToTips("登录失败！", "未知错误！");
        }

        //新浪登录
        public ActionResult SinaLogin()
        {
            Model.User loginUser = GetLoginUser();
            if (loginUser == null)
            {
                SinaApi sinaApi = new SinaApi();
                string state = Guid.NewGuid().ToString().Replace("-", "");
                Session["requeststate"] = state;
                var authenticationUrl = sinaApi.GetAuthorizationUrl(state);
                return new RedirectResult(authenticationUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        //新浪登录
        public ActionResult SinaCallback()
        {
            try
            {
                SinaApi sinaApi = new SinaApi();
                var state = Request.Params["state"];
                string requestState = Session["requeststate"].ToString();
                if (state == requestState)
                {
                    sinaApi.GetAccessToken(Request["code"]);
                    SinaUser sinaUser = sinaApi.GetUserInfo();
                    if (sinaUser == null)
                    {
                        return JumpToTips("读取用户信息失败", "对不起，读取您在新浪微博的帐号失败");
                    }
                    string accesstoken = sinaApi.Token.AccessToken;
                    string openId = sinaApi.Token.Uid;
                    if (sinaUser == null || string.IsNullOrEmpty(openId))
                    {
                        return JumpToTips("登录失败！", "授权错误！请稍后重试！");
                    }
                    BLL.User bllUser = new BLL.User();
                    Model.User mUser = bllUser.GetModelByOpenId(openId, Model.LoginType.Sina);
                    if (mUser == null)
                    {
                        mUser = new Model.User();
                        mUser.AreaID = 0;
                        mUser.Avatar = sinaUser.profile_image_url;
                        mUser.Birth = null;
                        mUser.Email = "";
                        mUser.Intro = sinaUser.description;
                        mUser.LoginCount = 0;
                        mUser.LoginIp = "";
                        mUser.LoginTime = null;
                        mUser.Mobile = "";
                        mUser.Username = "";
                        mUser.Nickname = sinaUser.name;
                        mUser.Password = "";
                        mUser.Privacy = 0;
                        mUser.RegIp = Helper.Util.GetIP();
                        mUser.RegTime = DateTime.Now;
                        mUser.Sex = (sinaUser.gender == "m" ? 1 : 2);
                        mUser.Sign = "此家伙不懒，就是什么也没留下";
                        mUser.State = 0;
                        mUser.Vip = 0;
                        mUser.Credit = 5;   //初次登录赠送5个积分
                        mUser.Money = 0;
                        mUser.Config = new UserConfig();
                        //用户尚未注册
                        mUser.LoginType = Model.LoginType.Sina;
                        mUser.AccessToken = accesstoken;
                        mUser.OpenId = openId;
                        mUser.AuthTime = DateTime.Now;
                        mUser.UserID = bllUser.Add(mUser);
                    }
                    else
                    {
                        switch (Config.LoginLimit)
                        {
                            //禁止所有用户登录
                            case 2:
                                return JumpToTips("Error", "系统正在维护，暂停登录，请稍后再试！");
                            //break;

                            //只有激活用户可以登录
                            case 1:
                                if (mUser.State == 0)
                                {
                                    return JumpToTips("Error", "您的帐号尚未激活，请先登录邮箱激活帐号！");
                                }
                                else if (mUser.State == -1)
                                {

CengZai.Web/Views/OAuth/Register.cshtml
@{
    ViewBag.Title = "完善注册信息";
    CengZai.Model.User loginUser = Html.GetLoginUser();
    ViewBag.HideMenu = 1;
}

<div class="container bg-white">
<section class="padding">
    <div class="page-header"> 
        <h1>@ViewBag.Title</h1> 
    </div> 
    <div>
    @using (Html.BeginForm("Register", "OAuth", FormMethod.Post, new { @class = "well" }))
    {
        if (ViewBag.RegisterLimit == 1)
        {
        <p>
            <label for="username">邀请码：</label>
            @Html.TextBox("invite", "")
            @Html.ValidationMessage("invite") 
            <span class="muted">必须有邀请码才能注册
            （您可以接受朋友的邀请，或者 @Html.ActionLink("申请邀请码", "ApplyInvite")）
            </span>
        </p>
        }
        <p>
            <label for="username">邮 箱： </label>
            @Html.TextBox("email", loginUser != null ? loginUser.Email : "")
            @Html.ValidationMessage("email") <span class="alert">请真实填写，用来找回密码，不可修改</span>
        </p>
        <p>
            <label for="username">用户名：<span class="muted">用来做主页地址，如myname，则主页地址为：@Url.BlogUrl("myname")</span></label>
            @if (CengZai.Helper.Config.OpenBlogDomain == 1)
            {
                @Html.TextBox("username", loginUser != null ? loginUser.Username : "", new { @class = "input-small" })<text>.</text>@CengZai.Helper.Config.BlogDomain
            }
            else
            {
                @Html.TextBox("username", loginUser != null ? loginUser.Username : "")
            }
            @Html.ValidationMessage("username") <span class="alert">5~20位字符，字母开头，只能是英文、数字、下划线组合，不分大小写</span>
            
        </p>
        <p>
            <label for="username">真实姓名：</label>
            @Html.TextBox("nickname", "")
            @Html.ValidationMessage("nickname") <span class="alert">请输入<span style="color: red;font-weight: bold">真实中文姓名</span>，方便朋友查找</span>
        </p>
        <p>
            <label class="checkbox inline"> 
                <input type="checkbox" checked="checked" name="share" id="share" value="1"> 分享到 @CengZai.Helper.Util.GetDescription(loginUser.LoginType) <span class="muted">（方便朋友查找和联系）</span>
            </label> 
        </p>
        <p>
            <input type="submit" class="btn btn-primary" value="保存" />
        </p>
    }
    
    </div>
</section>
</div>

CengZai.Web/Views/OAuth/_OauthLoginLink.cshtml
<div class="oauth-link">
    <text>使用其它帐号登录:</text> 
    <img src="@Url.GetResourceUrl("/img/ico_qzone_16x16.png")" /> <a href="@Url.Action("QQLogin", "OAuth")">腾讯QQ</a>&nbsp;
    <img src="@Url.GetResourceUrl("/img/ico_sina_16x16.png")" /> <a href="@Url.Action("SinaLogin", "OAuth")">新浪微博</a>&nbsp;
    <img src="@Url.GetResourceUrl("/img/ico_sina_16x16.png")" /> <a href="@Url.Action("TestLogin", "OAuth")">测试登录</a>&nbsp;  
</div>