CengZai.Web/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CengZai.Web.Controllers
{
    public class AboutController : BaseController
    {
        //
        // GET: /About/

        public ActionResult Us()
        {
            return View();
        }



        public ActionResult Join()
        {
            return View();
        }


        public ActionResult Agreement()
        {
            return View();
        }



        public ActionResult Privacy()
        {
            return View();
        }


    }
}

CengZai.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CengZai.Helper;

namespace CengZai.Web.Controllers
{
    public class BlogController : BaseController
    {


        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            string username = filterContext.ActionParameters["username"] as string;

            #region __用户基本信息处理start__
            BLL.User bllUser = new BLL.User();
            BLL.Lover bllLover = new BLL.Lover();
            Model.User blogUser = bllUser.GetModelByCache(username);
            if (blogUser == null || blogUser.State == -1)
            {
                filterContext.Result = JumpToHome("对不起！", "您访问的博客不存在！");
                return;
            }
            ViewBag.BlogUser = blogUser;    //保存博客主
            string blogSkin = "";
            if (blogUser.Config != null && !string.IsNullOrEmpty(blogUser.Config.BlogSkin))
            {
                blogSkin = blogUser.Config.BlogSkin;
            }
            ViewBag.BlogSkin = blogSkin;
            Model.Lover blogLover = bllLover.GetAwardLover(blogUser.UserID);
            if (blogLover == null)
            {
                if (blogUser.Sex == 2)
                {
                    ViewBag.Girl = blogUser;
                }
                else
                {
                    ViewBag.Boy = blogUser;
                }
                return;
            }
            Model.User loverUser = null;
            if (blogLover.BoyUserID == blogUser.UserID)
            {
                loverUser = bllUser.GetModelByCache((int)blogLover.GirlUserID);
            }
            else
            {
                loverUser = bllUser.GetModelByCache((int)blogLover.BoyUserID);
            }
            if (loverUser == null)
            {
                return;
            }
            CengZai.Model.User boy = null;
            CengZai.Model.User girl = null;
            if (blogUser.Sex == 2)
            {
                girl = blogUser;
                boy = loverUser;
            }
            else
            {
                girl = loverUser;
                boy = blogUser;
            }
            //保存情侣信息
            ViewBag.BlogLover = blogLover;
            ViewBag.LoverUser = loverUser;
            ViewBag.Boy = boy;
            ViewBag.Girl = girl;
            #endregion __用户基本信息处理end__
        }

        //用户博客
        public ActionResult Blog(string username, int? pageid)
        {
            try
            {
                Model.User blogUser = ViewBag.BlogUser;
                Model.User loverUser = ViewBag.LoverUser;
                Model.User boy = ViewBag.Boy;
                Model.User girl = ViewBag.Girl;
                ViewBag.TotalCount = 0;
                if (blogUser == null)
                {
                    return JumpToHome("对不起！", "您访问的博客不存在！");
                }

                string userIds = blogUser.UserID.ToString();
                if (boy != null)
                {
                    userIds += "," + boy.UserID;
                }
                if (girl != null)
                {
                    userIds += "," + girl.UserID;
                }
                BLL.Article bllArt = new BLL.Article();
                List<Model.Article> artList = bllArt.GetUserPublicListByPage(userIds, "IsTop DESC,PostTime DESC", mPageSize, mPageIndex, out mTotalCount);
                SetPage();  //设置分页
                ViewBag.ArtList = artList;
                return View();
            }
            catch (Exception ex)
            {
                Log.Error("");
                return JumpToTips("操作失败", "对不起，可能网络出现问题，请稍后重试！");
            }
        }

        //用户资料
        public ActionResult Profile(string username)
        {
            return View();
        }

        //证件信息
        public ActionResult Certificate(string username, int? loverid)
        {
            Model.Lover lover = ViewBag.BlogLover as Model.Lover;
            if (lover == null)
            {
                return JumpToHome("证书不存在！", "对不起，您访问的证书不存在！");
            }
            return View();
        }

        //文章信息
        public ActionResult Article(string username, int? artid)
        {
            if (artid == null)
            {
                return JumpToTips("对不起，网页不存在", "对不起，网页不存在！");
            }
            try
            {
                Model.Article art = new BLL.Article().GetModel((int)artid);
                if (art == null)
                {
                    return JumpToTips("对不起，网页不存在", "对不起，网页不存在！");
                }
                Model.User user = new BLL.User().GetModel((int)art.UserID);
                if (user.Username != username)
                {
                    //如果不是原作者的，则跳转
                    return RedirectToAction("Article", new { username = user.Username, artid = art.ArtID });
                }
                try
                {
                    art.ViewCount = (art.ViewCount == null ? 1 : (art.ViewCount + 1));
                    new BLL.Article().Update(art);
                }
                catch (Exception ex)
                {
                    Log.Error("BlogController.Article()更新阅读量异常", ex);
                }
                ViewBag.Article = art;
            }
            catch (Exception ex)
            {
                Log.Error("BlogController.Article()读取文章异常", ex);
                return JumpToTips("对不起，网页出现异常", "对不起，网页出现异常！");
            }
            return View();
        }

    }
}

CengZai.Web/Controllers/InboxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CengZai.Web.Common;
using CengZai.Helper;
using System.Data;

namespace CengZai.Web.Controllers
{
    public class InboxController : BaseController
    {
        //
        // GET: /Inbox/
        /// <summary>
        /// 
        /// </summary>
        /// <param name="type">0=全部，1=私信，2=系统</param>
        /// <returns></returns>
        [CheckAuthFilter]
        public ActionResult Index(string active)
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return JumpToTips("您尚未登录", "您尚未登录");
                }
                List<Model.Inbox> list = null;
                
                BLL.Inbox bllInbox = new BLL.Inbox();
                string where = string.Format("ToUserID={0}", loginUser.UserID);
                if (active == "privacy")
                {
                    where += " and IsSystem=0 ";
                }
                else if (active == "notice")
                {
                    where += " and IsSystem=1 ";
                }
                else if (active == "unread")
                {
                    where += " and IsRead=0 ";
                }
                DataSet dsInboxList = bllInbox.GetList(0, where, "SendTime DESC");
                if (dsInboxList != null && dsInboxList.Tables.Count > 0)
                {
                    list = bllInbox.DataTableToList(dsInboxList.Tables[0]);
                }
                ViewBag.InboxList = list;

                int newCount = 0;
                DataSet dsUnReadList = bllInbox.GetList("IsRead=0 and ToUserID=" + loginUser.UserID);
                if (dsUnReadList != null && dsUnReadList.Tables.Count > 0)
                {
                    newCount = dsUnReadList.Tables[0].Rows.Count;
                }
                ViewBag.NewCount = newCount;
            }
            catch (Exception ex)
            {
                Log.Error("私信异常", ex);
            }
            return View();
        }

        [CheckAuthFilter]
        public ActionResult Send(int? toUserID)
        {
            
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return JumpToTips("操作错误", "您尚未登录！");
                }
                Model.User toUser = null;
                if (toUserID != null)
                {
                    toUser = new BLL.User().GetModel((int)toUserID);
                    
                }
                ViewBag.ToUser = toUser;
                if(toUser == null)
                {
                    //
                    int totalCount = 0;
                    DataSet dsList = new BLL.Friend().GetFriendUserListByPage(loginUser.UserID
                        , Model.FriendRelation.FollowOrFans
                        , ""
                        , 500, 1, out totalCount);
                    if (dsList != null && dsList.Tables.Count > 0)
                    {
                        ViewBag.FriendList = new BLL.User().DataTableToList(dsList.Tables[0]);
                    }
                }
                
                //if (toUser == null || toUser.State <= 0)
                //{
                //    return JumpToTips("操作错误！", "用户被锁定或者不存在！");
                //}
                //if (loginUser.UserID == toUserID)
                //{
                //    return JumpToTips("操作错误", "不能给自己发私信");
                //}
                
            }
            catch (Exception ex)
            {
                Log.Error("发送私信异常", ex);
            }
            return View();
        }

        [HttpPost]
        [CheckAuthFilter]
        public ActionResult Send(int? toUserID, string content)
        {
            if (toUserID == null)
            {
                return AjaxReturn("error", "请选择发送人");
            }
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return AjaxReturn("error", "您尚未登录！");
                }
                Model.User toUser = new BLL.User().GetModel((int)toUserID);
                if (toUser == null || toUser.State < 0)
                {
                    return AjaxReturn("error", "用户被锁定或者不存在！");
                }
                if (loginUser.UserID == toUserID)
                {
                    return AjaxReturn("error", "不能给自己发私信");
                }
                if (string.IsNullOrEmpty(content) || content.Trim().Length <= 0 || content.Length > 300)
                {
                    return AjaxReturn("error", "内容长度只能是1到300个字符之间");
                }
                Model.Inbox inbox = new Model.Inbox();
                inbox.Content = content;
                inbox.FromUserID = loginUser.UserID;
                inbox.IsDelete = 0;
                inbox.IsRead = 0;
                inbox.IsSystem = 0;
                inbox.SendTime = DateTime.Now;
                inbox.Title = "";
                inbox.ToUserID = toUser.UserID;
                if (new BLL.Inbox().Add(inbox) > 0)
                {
                    return AjaxReturn("success", "发送成功！");
                }
                else
                {
                    return AjaxReturn("error", "发送失败，请稍后重试！");
                }
            }
            catch (Exception ex)
            {
                Log.Error("发送私信异常", ex);
                return AjaxReturn("error", "发送出现异常");
            }
            
        }


        //设置已读
        [HttpPost]
        [CheckAuthFilter]
        public ActionResult AjaxSetRead()
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if(loginUser == null)
                {
                    return AjaxReturn("error", "您尚未登录！");
                }
                new BLL.Inbox().SetReadByUser(loginUser.UserID);
                return AjaxReturn("success", "设为已读成功！");
            }
            catch (Exception ex)
            {
                Log.Error("消息设置为已读失败", ex);
                return AjaxReturn("error", "设置为已读失败！");
            }
        }

        [CheckAuthFilter]
        public ActionResult Reply(int? msgid, int? touserid)
        {
            if (msgid != null)
            {
                try
                {
                    new BLL.Inbox().SetIsRead(msgid.ToString(), 1);
                }
                catch (Exception ex)
                {
                    Log.Error("消息设置为已读失败", ex);
                }
            }
            return RedirectToAction("Send", new { touserid = touserid });
        }



        [CheckAuthFilter]
        public ActionResult Read(int msgid)
        {
            return View();
        }


        //设置已读
        [CheckAuthFilter]
        public ActionResult AjaxGetNewCount()
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return AjaxReturn("error", "您尚未登录！");
                }
                int count = 0;
                BLL.Inbox bllInbox = new BLL.Inbox();
                string where = string.Format("ToUserID={0} and IsRead=0 ", loginUser.UserID);
                DataSet dsInboxList = bllInbox.GetList(where);
                if (dsInboxList != null && dsInboxList.Tables.Count > 0)
                {
                    count = dsInboxList.Tables[0].Rows.Count;
                }
                return AjaxReturn("success", count.ToString());
            }
            catch (Exception ex)
            {
                Log.Error("消息设置为已读失败", ex);
                return AjaxReturn("error", "0");
            }
        }

    }
}

CengZai.Web/Controllers/SquareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CengZai.Helper;

namespace CengZai.Web.Controllers
{
    public class SquareController : BaseController
    {
        //
        // GET: /Square/



        /// <summary>
        /// 广场
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            try
            {
                BLL.Lover bllLover = new BLL.Lover();
                //取最新列表
                ViewBag.TopLoverList = bllLover.GetModelList(200, "State=1", "ApplyTime ASC,JoinDate ASC");
            }
            catch (Exception ex)
            {
                Log.Error("Square/Index异常", ex);
                return JumpTo("对不起，出错了", "哎呀，对不起！出错了，请刷新或者稍后访问！", "", 0);
            }
            return View();
        }

    }
}

CengZai.Web/Views/Shared/JumpTo.cshtml
@{
    if (ViewBag.Title == null)
    {
        ViewBag.Title = "跳转提示";
    }
    if (ViewBag.Message == null)
    {
        ViewBag.Message = "正在跳转，请稍后...";
    }
    if (ViewBag.Time == null)
    {
        ViewBag.Time = 5;//5秒
    }
}
@section head{
    @if (!string.IsNullOrEmpty(ViewBag.Url))
    {
        <text><meta http-equiv="refresh" content="@ViewBag.Time;url=@ViewBag.Url"></text>
    }
}

<div class="container  bg-white">

        <div class="padding">

            <!--登记表单-->
            <fieldset>
            <legend>@ViewBag.Title</legend>
                
                <p style="padding:20px 10px; line-height:2em; font-size:14px;">@MvcHtmlString.Create(ViewBag.Message)</p>
                
                @if (@ViewBag.Time > 0 && !string.IsNullOrEmpty(ViewBag.Url))
                {
                    <p class="help-block">
                        本页面将在<b>@ViewBag.Time</b>秒后自动跳转，如果没有跳转，<a href="@ViewBag.Url">请点击这里</a>
                    </p>
                }
            </fieldset>
      </div>
</div>




CengZai.Web/Views/Shared/_AboutNavList.cshtml
@{
    Layout = null;
}

<ul class="nav nav-list"> 
    <li class="nav-header"><text>关于</text>@ViewBag.SiteName</li> 
    <li @if (@PageData["Active"] == "Us"){<text>class="active"</text>}>
        @Html.ActionLink("联系我们", "Us", "About")
    </li> 
    <li @if (@PageData["Active"] == "Join"){<text>class="active"</text>}>
        @Html.ActionLink("加入我们", "Join", "About")
    </li> 
    <li @if (@PageData["Active"] == "Agreement") {<text>class="active"</text>}>
        @Html.ActionLink("用户协议", "Agreement", "About")
    </li>
    <li @if (@PageData["Active"] == "Privacy") {<text>class="active"</text>}>
        @Html.ActionLink("隐私策略", "Privacy", "About")
    </li> 
</ul>

CengZai.Web/Views/Shared/_Footer.cshtml
@{
    Layout = null;
}

<footer class="container">
    <p class="pull-left">&copy 2012 <a href="@ViewBag.SiteHost">@ViewData["SiteName"]<text>(</text>@ViewData["SiteDomain"])</a></p>
    <div class="pull-right">
        @Html.ActionLink("情侣广场", "Index", "Square") | 
        @Html.ActionLink("关于我们", "Us", "About") | 
        @Html.ActionLink("用户协议", "Agreement", "About") | 
        @*@Html.ActionLink("隐身政策", "Privacy", "About") | *@
            
        <a href="http://www.miibeian.gov.cn" target="_blank">粤ICP备11056743号</a>
    </div>
</footer>
<script type="text/javascript" src="http://js.tongji.linezing.com/2807601/tongji.js"></script><noscript><a href="http://www.linezing.com"><img src="http://img.tongji.linezing.com/2807601/tongji.gif"/></a></noscript>

CengZai.Web/Views/Shared/_Layout.cshtml
@{
    
}
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.SiteName - @ViewBag.Title</title>
    <meta name="keywords" content="@ViewBag.SiteKeyword" />
    <meta name="description" content="@ViewBag.SiteDescription" />
    <meta property="qc:admins" content="1541240606635672116375" />
    <link href="@Url.GetResourceUrl("/css/bootstrap.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.GetResourceUrl("/css/style.css")" rel="stylesheet" type="text/css" />
    
    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="@Url.GetResourceUrl("/js/html5.js")" type="text/javascript"></script>
    <![endif]-->
    <script src="@Url.GetResourceUrl("/js/jquery.min.js")" type="text/javascript"></script>
    <script src="@Url.GetResourceUrl("/js/bootstrap.min.js")" type="text/javascript"></script>
    <script src="@Url.GetResourceUrl("/js/mvc/MicrosoftAjax.js")" type="text/javascript"></script> 
    <script src="@Url.GetResourceUrl("/js/mvc/MicrosoftMvcAjax.js")" type="text/javascript"></script>
    <script src="@Url.GetResourceUrl("/js/mvc/jquery.unobtrusive-ajax.min.js")" type="text/javascript"></script>
    <link href="@Url.GetResourceUrl("/js/dialog/skins/twitter.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.GetResourceUrl("/js/dialog/jquery.artDialog.min.js")" type="text/javascript"></script>
    <script src="@Url.GetResourceUrl("/js/dialog/artDialog.plugins.min.js")" type="text/javascript"></script>
    <script src="@Url.GetResourceUrl("/js/core.js")" type="text/javascript"></script>
    <link rel="shortcut icon" href="@Url.GetResourceUrl("img/favicon.ico")">
@*    <!-- Le fav and touch icons -->
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">*@
    @RenderSection("head", false)
</head>

<body>
@Html.Partial("_Topbar")

@RenderBody()

<hr class="hr-gray" />

@Html.Partial("_Footer")
</body>
</html>


CengZai.Web/Views/Shared/_Topbar.cshtml
@{
    Layout = null;
    var user = Html.GetLoginUser() as CengZai.Model.User;
            //ViewBag.HideMenu 是否隐藏，1则隐藏
}

<header class="navbar navbar-fixed-top">
	<div class="navbar-inner">
	<div class="container">
		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		<span class="icon-bar"></span>
		</a>
		<a class="brand logo" href="@ViewBag.SiteHost">@ViewBag.SiteName</a>
        @if (ViewBag.HideMenu != 1)
        {
		<div class="nav-collapse">
        @if (user != null)
        {
		    <ul class="nav">
			    <li class="active">@Html.HttpActionLink("首页", "Index", "Home", null, null)</li>
                <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">发表<b class="caret"></b></a> 
                    <ul class="dropdown-menu"> 
                        <li>@Html.HttpActionLink("日志", "PostText", "Article")</li> 
                        <li>@Html.HttpActionLink("私信", "Send", "Inbox")</li>
                        <li class="divider"></li> 
                        <li>@Html.HttpActionLink("日志管理", "Index", "Article")</li>
                    </ul> 
                </li>
                <li>@Html.HttpActionLink("我的主页", "Blog", "Blog", new { username = user.Username }, null)</li>
                <li><a href="@Url.HttpAction("Index", "Lover")">情侣<sup id="loverNewCount" class="label label-important hide">0</sup></a></li>
			    <li>@Html.HttpActionLink("好友", "List", "Friend")</li>
		    </ul>
            <!--<form class="navbar-form pull-left" action="">-->
            <form method="get" action="@Url.Action("Find", "Friend")" class="navbar-form pull-left">
                <div class="input-append">
                    <input type="text" name="keyword" class="span2" id="appendedPrependedInput" size="16"  placeholder="搜索感兴趣的人"><input type="submit" class="btn" value="搜索" />
                </div>
            </form>
            <!--</form>-->
            <ul class="nav pull-right nav-mini-link">
                <li class="dropdown"> 
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">@user.Nickname <b class="caret"></b></a> 
                    <ul class="dropdown-menu"> 
                    <li>@Html.HttpActionLink("上传头像", "Avatar", "Settings")</li> 
                    <li>@Html.HttpActionLink("修改资料", "Profile", "Settings")</li> 
                    <li>@Html.HttpActionLink("修改密码", "Password", "Settings")</li> 
                    <li class="divider"></li> 
                    <li>@Html.HttpActionLink("退出", "Logout", "Account")</li> 
                    </ul> 
                </li>
                <li class="divider-vertical"></li> 
                <li><a href="@Url.HttpAction("Index", "Inbox", new { active = "unread" })">消息<sup id="inboxNewCount" class="label label-success hide">0</sup></a></li>
                <li>@Html.HttpActionLink("邀请", "Invite", "Friend")</li> 
                <li>@Html.HttpActionLink("退出", "Logout", "Account")</li>
            </ul>
        }
        else
        {
            <ul class="nav">
                <li>@Html.HttpActionLink("登录", "Index", "Home")</li>
		    </ul>
            <p class="navbar-text pull-right">还有没有注册曾在网？ @Html.HttpActionLink("立刻注册", "Register", "Account")</p>
        }
		</div><!--/.nav-collapse -->
        }
	</div>
	</div>
</header>
<!-- navbar 结束 -->