CengZai.Web/Controllers/FriendController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CengZai.Web.Common;
using CengZai.Helper;
using System.Data;

namespace CengZai.Web.Controllers
{
    public class FriendController : BaseController
    {
        //
        // GET: /Friend/

        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="active">friend=朋友（互相关注）, follow=我关注,fans=关注我，black=黑名单</param>
        /// <returns></returns>
        [CheckAuthFilter]
        public ActionResult List(string active)
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                BLL.Friend bllFriend = new BLL.Friend();
                int pageSize = 20;
                int totalCount = 0;
                int pageIndex = GetPageIndex("page");
                DataSet dsList = null;
                //处理
                if (active == "follow")
                {
                    dsList = bllFriend.GetFriendUserListByPage(loginUser.UserID, Model.FriendRelation.Follow
                        , "", pageSize, pageIndex, out totalCount);
                }
                else if (active == "fans")
                {
                    dsList = bllFriend.GetFriendUserListByPage(loginUser.UserID, Model.FriendRelation.Fans
                        , "", pageSize, pageIndex, out totalCount);
                }
                else if (active == "black")
                {
                    dsList = bllFriend.GetFriendUserListByPage(loginUser.UserID, Model.FriendRelation.Black
                        , "", pageSize, pageIndex, out totalCount);
                }
                else
                {
                    dsList = bllFriend.GetFriendUserListByPage(loginUser.UserID, Model.FriendRelation.Friend
                        , "", pageSize, pageIndex, out totalCount);
                }
                if (dsList != null && dsList.Tables.Count > 0)
                {
                    List<Model.User> userList = new BLL.User().DataTableToList(dsList.Tables[0]);
                    ViewBag.UserList = userList;
                }
            }
            catch (Exception ex)
            {
                Log.Error("批量关注朋友页面出现异常！", ex);
                return JumpToAction("页面出现异常", "即将跳转到完善资料页面...", "Avatar", "Settings");
            }
            return View();
        }


        /// <summary>
        /// 查找朋友
        /// </summary>
        /// <returns></returns>
        [CheckAuthFilter]
        public ActionResult Find(string keyword)
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                bool isUsePager = false;
                BLL.User bllUser = new BLL.User();
                DataSet dsList = null;
                if (!string.IsNullOrEmpty(keyword))
                {
                    dsList = bllUser.GetListBySearch(100, keyword, "RegTime DESC");
                    if (dsList == null || dsList.Tables.Count == 0 || dsList.Tables[0].Rows.Count == 0)
                    {
                        return JumpToAction("找不到关键词“" + keyword + "”的用户", "对不起，找不到关键词为“" + keyword + "”的用户，您可以试试搜索昵称、用户名或邮箱进行查找。", "Find");
                    }
                }
                else
                {
                    isUsePager = true;
                    dsList = bllUser.GetListByPage("State>=0", "UserID ASC", mPageSize, mPageIndex, out mTotalCount);
                    SetPage();
                }
                ViewBag.UsePager = isUsePager;  //是否使用分页
                if (dsList != null && dsList.Tables.Count > 0)
                {
                    List<Model.User> userList = bllUser.DataTableToList(dsList.Tables[0]);
                    Model.User currUser = userList.Find(x => x.UserID == loginUser.UserID);
                    if (currUser != null)
                    {
                        userList.Remove(currUser);  //移除自己
                    }
                    ViewBag.UserList = userList;
                }
            }
            catch (Exception ex)
            {
                Log.Error("批量关注朋友页面出现异常！", ex);
                return JumpToAction("页面出现异常", "即将跳转到完善资料页面...", "Avatar", "Settings");
            }
            return View();
        }

        /// <summary>
        /// 关注朋友处理
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [CheckAuthFilter]
        public ActionResult Find(int[] userid)
        {
            try
            {
                int feedCount = 0;
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                if (userid != null && userid.Length > 0)
                {
                    BLL.Friend bllFriend = new BLL.Friend();
                    foreach (int friendUserID in userid)
                    {
                        if (bllFriend.Add(loginUser.UserID, friendUserID))
                        {
                            feedCount++;
                        }
                    }
                }
                if (feedCount > 0)
                {
                    return JumpBackAndRefresh("关注成功", "恭喜您，关注成功，一共关注" + feedCount + "个好友，您以后可以随时关注更多或者取消！");
                }
                else
                {
                    return JumpBackAndRefresh("关注失败", "对不起，关注" + feedCount + "个用户！");
                }
            }
            catch (Exception ex)
            {
                Log.Error("Find(int[] userid)关注用户提交失败！", ex);
                return JumpBackAndRefresh("关注失败", "对不起，关注出现异常");
            }
        }

        /// <summary>
        /// Ajax添加朋友
        /// </summary>
        /// <returns></returns>
        public ActionResult FriendAdd(int? friendUserID)
        {
            try
            {
                if(friendUserID == null)
                {
                    return AjaxReturn("-1", "对方ID为空");
                }
                Model.User user = GetLoginUser();
                if(user == null)
                {
                    return AjaxReturn("-1", "您尚未登录，请先登录或者注册！");
                }
                BLL.Friend bllFriend = new BLL.Friend();
                Model.Friend isExist = bllFriend.GetModel(user.UserID, (int)friendUserID);
                if (isExist != null)
                {
                    return AjaxReturn("0", "您已经关注，无需重复关注！");
                }
                if (bllFriend.Add(user.UserID, (int)friendUserID))
                {
                    return AjaxReturn(friendUserID.ToString(), "关注成功！");
                }
                else
                {
                    return AjaxReturn("0", "关注失败，请稍后重试！");
                }
            }
            catch (Exception ex)
            {
                Log.Error("添加用户异常", ex);
                return AjaxReturn("-1", "出现异常！");
            }
        }


        /// <summary>
        /// Ajax添加朋友
        /// </summary>
        /// <returns></returns>
        public ActionResult FriendDel(int? friendUserID)
        {
            try
            {
                if (friendUserID == null)
                {
                    return AjaxReturn("-1", "对方ID为空");
                }
                Model.User user = GetLoginUser();
                if (user == null)
                {
                    return AjaxReturn("-1", "您尚未登录，请先登录或者注册！");
                }
                BLL.Friend bllFriend = new BLL.Friend();
                Model.Friend isExist = bllFriend.GetModel(user.UserID, (int)friendUserID);
                if (isExist == null)
                {
                    return AjaxReturn("0", "您尚未关注！");
                }
                if (bllFriend.Delete(isExist.ID))
                {
                    return AjaxReturn(friendUserID.ToString(), "取消关注成功！");
                }
                else
                {
                    return AjaxReturn("0", "取消关注失败，请稍后重试！");
                }
            }
            catch (Exception ex)
            {
                Log.Error("取消关注异常", ex);
                return AjaxReturn("-1", "出现异常！");
            }
        }


        /// <summary>
        /// 关注朋友
        /// </summary>
        /// <returns></returns>
        [CheckAuthFilter]
        public ActionResult FeedFriendsForFirstLogin()
        {
            try
            {
                Model.User loginUser = GetLoginUser();
                if (loginUser == null)
                {
                    return RedirectToAction("Login", "Account");
                }
                BLL.User bllUser = new BLL.User();
                DataSet dsList = bllUser.GetList(100, "State=1 and UserID<>" + loginUser.UserID, "Vip DESC, RegTime DESC");
                if (dsList != null && dsList.Tables.Count > 0)
                {
                    ViewBag.UserList = bllUser.DataTableToList(dsList.Tables[0]);
                }
                else
                {
                    return JumpToAction("暂无用户", "即将跳转到完善资料页面...", "Avatar", "Settings");
                }
            }
            catch (Exception ex)
            {
                Log.Error("批量关注朋友页面出现异常！", ex);
                return JumpToAction("页面出现异常", "即将跳转到完善资料页面...", "Avatar", "Settings");
            }
            return View();
        }



CengZai.Web/Views/Friend/FeedFriendsForFirstLogin.cshtml
@{
    ViewBag.Title = "关注朋友";
    var userList = ViewBag.UserList as List<CengZai.Model.User>;
}
@section head{
<script type="text/javascript">
    $(document).ready(function () {
        $("input[name='selAll']").click(function () {
            if ($(this).attr("checked")) {
                $("input[name='userid']").attr("checked", true);
            }
            else {
                $("input[name='userid']").attr("checked", false);
            }
        });
    });
</script>
}

<div class="container bg-white">
<div class="padding">
    <h2>@ViewBag.Title</h2>

    @using (Html.BeginForm())
    {
    <table class="table">
        <thead>
        <tr>
            <th><input name="selAll" type="checkbox" value="0" /></th>
            <th>头像</th>
            <th>昵称</th>
            <th>性别</th>
            <th>签名</th>
            <th>关注</th>
        </tr>
        </thead>
        <tbody>
        @if (userList != null)
        {
            foreach (CengZai.Model.User user in userList)
            {
                <tr>
                    <td><input name="userid" checked="checked" type="checkbox" value="@user.UserID" /></td>
                    <td><img src="@Url.GetAvatarUrl(user.Avatar)" alt="@user.Nickname" width="50" /></td>
                    <td>@user.Nickname</td>
                    <td>@Html.GetUserSexName(user.Sex)</td>
                    <td>@user.Sign</td>
                    <td>@Ajax.GetFriendAddLink(user.UserID, null)</td>
                </tr>
            }
        }
        </tbody>
    </table>
    <div>
        <input type="submit" value="关注选中用户" class="btn btn-primary" /> &nbsp;&nbsp; @Html.ActionLink("跳过", "Avatar", "Settings")
    </div>
    }
</div>
</div>   
<!--/.container -->

CengZai.Web/Views/Friend/Find.cshtml
@{
    ViewBag.Title = "搜索用户";
    var userList = ViewBag.UserList as List<CengZai.Model.User>;
}
@section head{
<script type="text/javascript">
    $(document).ready(function () {
        $("input[name='selAll']").click(function () {
            if ($(this).attr("checked")) {
                $("input[name='userid']").attr("checked", true);
            }
            else {
                $("input[name='userid']").attr("checked", false);
            }
        });
    });
</script>
}

<div class="container bg-white">
<div class="padding">
    <div class="row-fluid">
        <div class="span8"><h2>@ViewBag.Title</h2></div>
        <div class="span4">
        @using (Html.BeginForm("Find", "Friend", FormMethod.Get, new { @class = "navbar-form" }))
        {
            <span class="input-append">
                <input type="text" name="keyword" value="@Request["keyword"]" class="span2" id="appendedPrependedInput" size="16"  placeholder="搜索感兴趣的人"><input type="submit" class="btn" value="搜索" />
            </span>
            <a href="@Url.Action("Find", "Friend")" class="btn btn-success">随机看看</a>
        }
        </div>
    </div>

    @using (Html.BeginForm())
    {
    <table class="table">
        <thead>
        <tr>
            <th><input name="selAll" type="checkbox" value="0" /></th>
            <th>头像</th>
            <th>昵称</th>
            <th>性别</th>
            <th>签名</th>
            <th>关注</th>
        </tr>
        </thead>
        <tbody>
        @if (userList != null)
        {
            foreach (CengZai.Model.User user in userList)
            {
                <tr>
                    <td><input name="userid" type="checkbox" value="@user.UserID" /></td>
                    <td><a href="@Url.BlogUrl(user.Username, true)" title="访问Ta的主页" target="_blank"><img src="@Url.GetAvatarUrl(user.Avatar)" alt="@user.Nickname" width="50" /></a></td>
                    <td><a href="@Url.BlogUrl(user.Username, true)" title="访问Ta的主页" target="_blank">@user.Nickname</a></td>
                    <td>@Html.GetUserSexName(user.Sex)</td>
                    <td>@user.Sign</td>
                    <td>@Ajax.GetFriendAddLink(user.UserID, null)</td>
                </tr>
            }
        }
        </tbody>
    </table>
    <div>
        <input type="submit" value="关注选中用户" class="btn btn-primary" /> &nbsp;&nbsp; @Html.ActionLink("取消", "Avatar", "Settings")
    </div>
    }
    @if (ViewBag.UsePager)
    {
        <div class="pager"> @Html.Pager() </div>
    }
</div>
</div>   
<!--/.container -->

CengZai.Web/Views/Friend/Invite.cshtml
@{
    ViewBag.Title = "邀请用户";
    var loginUser = Html.GetLoginUser();
    var price = CengZai.Helper.Config.InviteCredit;
    var inviteList = ViewBag.InviteList as List<CengZai.Model.InviteCode>;
}
@section head{
<script type="text/javascript">
    $(document).ready(function () {
        $("input[name='selAll']").click(function () {
            if ($(this).attr("checked")) {
                $("input[name='userid']").attr("checked", true);
            }
            else {
                $("input[name='userid']").attr("checked", false);
            }
        });
    });
</script>
}

<div class="container bg-white">
<div class="padding">
    <h2>@ViewBag.Title</h2>
    <hr />
    <p>
        温馨提示，邀请朋友会@(price < 0 ? "扣除":"奖励") @Math.Abs(price) 个积分，您现在的积分是 @loginUser.Credit 个积分。
    </p>

    @if (inviteList != null && inviteList.Count > 0)
    {
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>邀请码</th>
                <th>邀请网址（复制发送给朋友即可）</th>
                <th>受邀请邮箱</th>
                <th>状态</th>
            </tr>
            @for (int i = 0; i < inviteList.Count; i++)
            {
            <tr>
                <td>@inviteList[i].Invite</td>
                <td>@CengZai.Helper.Util.GetCurrDomainUrl()@Url.Action("Register", "Account", new {invite = inviteList[i].Invite })</td>
                <td>@inviteList[i].Email</td>
                <td>有效</td>
            </tr>
            }
        </thead>
    </table>
    }
    <p>
        @if (price < 0 && (loginUser.Credit + price) < 0)
        {
            <p class="alert alert-block">囧，您的积分不够，您暂时不能邀请用户。</p>
        }
        else
        {
            using (Html.BeginForm("Invite", "Friend", FormMethod.Post, new { @class = "well form-inline" }))
            {
                <div>
                    @Html.TextBox("email", "", new { @class = "span3", size = "16", placeholder = "请输入被邀请人的邮箱" })
                    <label class="checkbox">
                      <input type="checkbox" name="sendmail" value="1" checked="checked">邮件通知
                    </label>
                    <input type="submit" class="btn" value="邀请" />
                </div>
                <p>@Html.ValidationMessage("error")</p>
            }
        }
    </p>
</div>
</div>   
<!--/.container -->

CengZai.Web/Views/Friend/List.cshtml
@{
    ViewBag.Title = "好友管理";
    var userList = ViewBag.UserList as List<CengZai.Model.User>;
    var active = Request["active"];
}
@section head{
<script type="text/javascript">
    $(document).ready(function () {
        $("input[name='selAll']").click(function () {
            if ($(this).attr("checked")) {
                $("input[name='userid']").attr("checked", true);
            }
            else {
                $("input[name='userid']").attr("checked", false);
            }
        });
    });
</script>
}

<div class="container bg-white">
<div class="padding">
    <div class="row-fluid">
        <div class="span8"><h2>@ViewBag.Title</h2></div>
        <div class="span4">
        @using (Html.BeginForm("Find", "Friend", FormMethod.Get, new { @class = "navbar-form" }))
        {
            <span class="input-append">
                <input type="text" name="keyword" value="@Request["keyword"]" class="span2" id="appendedPrependedInput" size="16"  placeholder="搜索感兴趣的人"><input type="submit" class="btn" value="搜索" />
                
            </span>
            <a href="@Url.Action("Find", "Friend")" class="btn btn-success">随机看看</a>
            
        }
        </div>
    </div>
    <div>
    <ul class="nav nav-tabs">
        <li @if (active == "friend" || string.IsNullOrEmpty(active))
            {<text>class="active"</text>}>@Html.ActionLink("朋友（互相关注）", "List", new { active = "friend" })</li>
        <li @if (active == "follow")
            {<text>class="active"</text>}>@Html.ActionLink("我关注", "List", new { active = "follow" })</li>
        <li @if (active == "fans")
            {<text>class="active"</text>}>@Html.ActionLink("关注我", "List", new { active = "fans" })</li>
        <li @if (active == "black")
            {<text>class="active"</text>}>@Html.ActionLink("黑名单", "List", new { active = "black" })</li>
    </ul>
    </div>



    <!--用户列表-->
    <div class="tab-content">
        <div class="tab-pane active">
        @using (Html.BeginForm("EditFriend", "Friend"))
        {
            <table class="table">
                <thead>
                <tr>
                    <th><input name="selAll" type="checkbox" value="0" /></th>
                    <th>头像</th>
                    <th>昵称</th>
                    <th>性别</th>
                    <th>签名</th>
                    <th>关注</th>
                    <th>私信</th>
                </tr>
                </thead>
                <tbody>
                @if (userList != null)
                {
                    foreach (CengZai.Model.User user in userList)
                    {
                        <tr>
                            <td><input name="userid" type="checkbox" value="@user.UserID" /></td>
                            <td><a href="@Url.BlogUrl(user.Username, true)" title="访问Ta的主页" target="_blank"><img src="@Url.GetAvatarUrl(user.Avatar)" alt="@user.Nickname" width="50" /></a></td>
                            <td><a href="@Url.BlogUrl(user.Username, true)" title="访问Ta的主页" target="_blank">@user.Nickname</a></td>
                            <td>@Html.GetUserSexName(user.Sex)</td>
                            <td>@user.Sign</td>
                            <td>@Ajax.GetFriendAddLink(user.UserID, null)</td>
                            <td>@Html.ActionLink("发送私信", "Send", "Inbox", new { touserid = user.UserID }, null)</td>
                        </tr>
                    }
                }
                </tbody>
            </table>
            <div>
                <input type="hidden" name="type" value="@(active == "black" ? "0" : "-1")" />
                @if (active == "black")
                {
                    <input type="submit" value="移除黑名单" class="btn btn-primary" />
                }
                else
                {
                    <input type="submit" value="加入黑名单" class="btn btn-danger" />
                }
            </div>
            }
        </div>
    </div>
    <!--/用户列表-->

</div>
</div>   
<!--/.container -->